AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Cevixe Stack - Core

Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Handler: handler
    MemorySize: 128
    Environment:
      Variables:
        CVX_GRAPHQL_GATEWAY_URL:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'GraphqlGatewayUrl'
        CVX_EVENT_BUS_ARN:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'EventBusArn'
        CVX_EVENT_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'EventStoreName'
        CVX_CONTROL_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'ControlStoreName'
        CVX_STATE_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'StateStoreName'
        CVX_OBJECT_STORE_NAME:
          Fn::ImportValue:
            Fn::Join:
              - "-"
              - - !Ref ApplicationName
                - 'ObjectStoreName'

Parameters:
  ApplicationName:
    Type: String
    MaxLength: 120
    Description: cevixe application name

Resources:
  DomainEventQueueFnQueue:
    Type: AWS::SQS::Queue
  NotifyEventHandlerFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventBusTopicName'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventStoreStreamArn'
            BatchSize: 25
            StartingPosition: TRIM_HORIZON
  NotifyGraphqlApiFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
        - Statement:
            - Sid: AppSyncLambdaClientPolicy
              Effect: Allow
              Action:
                - appsync:GraphQL
              Resource:
                - Fn::Join:
                    - "/"
                    - - Fn::ImportValue:
                          Fn::Join:
                            - "-"
                            - - !Ref ApplicationName
                              - 'GraphqlGatewayArn'
                      - '*'
      Events:
        DomainEvent:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventBusArn'
            SqsSubscription:
              BatchSize: 10
              QueueArn: !GetAtt DomainEventQueueFnQueue.Arn
              QueueUrl: !Ref DomainEventQueueFnQueue
              FilterPolicy:
                event_class:
                  - D
  UpdateStateStoreFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'ObjectStoreName'
        - DynamoDBWritePolicy:
            TableName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'StateStoreName'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - !Ref ApplicationName
                    - 'EventStoreStreamArn'
            BatchSize: 25
            StartingPosition: TRIM_HORIZON
